---
title: "AzureDSR Introduction"
author: "ADS Asia Pacific, Microsoft"
date: "`r Sys.Date()`"
# output: rmarkdown::html_vignette
output: github_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

**This vignette works as the blurprint before the package is released.**

# General Introduction

`AzureDSR` offers functions that can be conveniently used by R data scientists for managing Azure instances, remote executing scalable and elastic data analytical jobs, and monitoring cloud resource consumption.

# Preliminaries

1. An Azure account.
2. An initial setup for Active Directory following the instructions in `AzureSMR`. This is basically to get authentication confidentials that are used for using `AzureSMR` functions.

# `AzureDSR` functions

*Add your wish list here.*

## Resource

|Function|Description|
|------------------|-------------------------------------------------------------|
|`newLinuxDSVM`|Create a Linux DSVM with specific configurations such as size, name, DNS, etc.|
|`newWindowsDSVM`|Create a Windows DSVM with specific configurations such as size, name, DNS, etc.|
|`operateDSVM`|Check status of, start, stop, or delete an existing DSVM instance in a resource group.|

## Execution

`msrdeploy` of Microsoft R Client provides a bunch of handy functions for remote login, execution, etc...

What to do in `AzureDSR`: Generate an worker R script, which is then remotely executed with specific computing context, data reference, etc. This is taken care of by a interface object.

|Function|Description|

## Helpers

|Function|Description|
|------------------|-------------------------------------------------------------|
|`getVMSizeInfo`|Get information about DSVM. E.g., number of cores, memory size, and pricing details|
|`getDataConsumption`|Get data consumption of Azure subscription or a specific Azure instance under such subscription for a certain period|
|`getCost`|Calculate cost of Azure subscription or a specified instance under such subscription for a certain period of time (measured in a specified currency).|
